name = "image-background-remover"
compatibility_date = "2024-12-01"
account_id = "27aa59e3b803a4940abd0c34ae33fefe"
pages_build_output_dir = ".next"

[env.production]
name = "image-background-remover"

[vars]
REMOVE_BG_API_KEY = "8U73faZpDg7PghtR3t9bCdhc"